CRUD/urls.py
from django.urls import path
from . import views

app_name = 'CRUD'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout_view, name='logout_view'),
    path('', views.index, name='index'),
    path('guardar_contacto', views.guardar_contacto, name='guardar'),
    path('eliminar_contacto/<id>', views.eliminar_contacto, name='eliminar'),
    path('editar_contacto/<id>', views.editar_contacto, name='editar'),
    path('actualizar_contacto', views.actualizar_contacto, name='actualizar'),
]

Contactos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('CRUD.urls')),
]

CRUD/models.py
from django.db import models

# Create your models here.

# Se manejara una agenda de contactos con sus respectivos campos y CRUD

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)
    correo = models.EmailField(max_length=254)
    direccion = models.TextField()

    def __str__(self):
        return self.nombre + ' ' + self.apellido
    

CRUD/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.utils.translation import gettext_lazy as _
from .models import Contacto

# Create your views here.

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = 'El nombre de usuario debe ser menor a 150 caracteres y no puede contener caracteres especiales'
        self.fields['password1'].help_text = 'La contraseña debe tener al menos 3 caracteres'
        self.fields['password2'].help_text = 'La contraseña debe tener al menos 3 caracteres'

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('CRUD:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'autenticacion/register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'autenticacion/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('CRUD:login')


@login_required(login_url='CRUD:login')
def index(request):
    contactos = Contacto.objects.all()
    return render(request, 'index.html', {'contactos': contactos})

@login_required(login_url='CRUD:login')
def guardar_contacto(request):
    nombre = request.POST['txtnombre']
    apellido = request.POST['txtapellido']
    telefono = request.POST['txttelefono']
    correo = request.POST['txtcorreo']
    direccion = request.POST['txtdireccion']
    contacto = Contacto(nombre=nombre, apellido=apellido, telefono=telefono, correo=correo, direccion=direccion)
    contacto.save()
    return redirect('/')

@login_required(login_url='CRUD:login')
def eliminar_contacto(request, id):
    contacto = Contacto.objects.get(pk=id)
    contacto.delete()
    return redirect('/')

@login_required(login_url='CRUD:login')
def editar_contacto(request, id):
    contactoseleccionado = Contacto.objects.get(pk=id)
    contactos = Contacto.objects.all()
    context = {'contactos': contactos, 'contactoseleccionado': contactoseleccionado}
    return render(request, 'editar_contacto.html', context)

@login_required(login_url='CRUD:login')
def actualizar_contacto(request):
    nombre = request.POST['txtnombre']
    apellido = request.POST['txtapellido']
    telefono = request.POST['txttelefono']
    correo = request.POST['txtcorreo']
    direccion = request.POST['txtdireccion']

    contacto = Contacto.objects.get(pk=request.POST['id'])
    contacto.nombre = nombre
    contacto.apellido = apellido
    contacto.telefono = telefono
    contacto.correo = correo
    contacto.direccion = direccion
    contacto.save()
    return redirect('/')

CRUD/templates/autenticacion/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Iniciar Sesión</title>
</head>
<body class="m-5">
    <h2 class="text-center">Iniciar Sesión</h2>
    <br>
    <form method="post" class="col-md-3 mx-auto border border-2 border-primary rounded p-3 justify-content-center">
        {% csrf_token %}
        {{ form.as_p }}
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-lg"
          style="padding-left: 2.5rem; padding-right: 2.5rem;">Ingresar</button>
        <p class="small fw-bold mt-2 pt-1 mb-0">¿No tienes una cuenta? 
            <a href="{% url 'CRUD:register' %}"
            class="link-danger">Registrarse</a></p>
      </div>
    </form>
</body>

</html>

CRUD/templates/autenticacion/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Registro</title>
</head>
<body class="m-5">
    <h2 class="text-center">Registro</h2>
    {% if error_message %}
        <p class="text-center text-danger">{{ error_message }}</p>
    {% endif %}
    <br>
    <form method="post" class="col-md-6 mx-auto border border-2 border-primary rounded p-3 justify-content-center">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
        <button type="submit" class="btn btn-primary mt-2 justify-content-center">Registrarse</button>
        <p class="text-center mt-3">¿Ya tienes una cuenta? <a href="{% url 'CRUD:login' %}">Iniciar sesión</a></p>
        </div>
    </form>
</body>
</html>

CRUD/templates/editar_contacto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>
        Editar Contacto
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Gestion de Contactos</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CRUD:index' %}">
              Contactos
            </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
            <!--Boton a la derecha del todo para el logout-->
            <li class="float-right">
              <a class="btn btn-danger nav-link float-right"
              href="{% url 'CRUD:logout_view' %}">
                Logout
              </a>
            </li>
          </ul>
      </div>
    </div>
  </nav>
  <br>
<div class="container">
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
        <h3>Editar Contacto</h3>
            <div class="card">
                <div class="card-body">
                        <form action="/actualizar_contacto" method="POST">
                            {%csrf_token%}
                            <input type="hidden" name="id" value="{{contactoseleccionado.id}}">
                            <div class="form-group mt-2">
                                <label for="txtnombre">Nombre</label>
                                <input type="text" class="form-control" id="txtnombre" name="txtnombre" value="{{contactoseleccionado.nombre}}">
                            </div>
                            <div class="form-group mt-2">
                                <label for="txtapellido">Apellido</label>
                                <input type="text" class="form-control" id="txtapellido" name="txtapellido" value="{{contactoseleccionado.apellido}}">
                            </div>
                            <div class="form-group mt-2">
                                <label for="txttelefono">Telefono</label>
                                <input type="text" class="form-control" id="txttelefono" name="txttelefono" value="{{contactoseleccionado.telefono}}">
                            </div>
                            <div class="form-group mt-2">
                                <label for="txtcorreo">Correo</label>
                                <input type="text" class="form-control" id="txtcorreo" name="txtcorreo" value="{{contactoseleccionado.correo}}">
                            </div>
                            <div class="form-group mt-2">
                                <label for="txtdireccion">Direccion</label>
                                <input type="text" class="form-control" id="txtdireccion" name="txtdireccion" value="{{contactoseleccionado.direccion}}">
                            </div>
                            <div class="form-group mt-3">
                                <button type="submit" class="btn btn-primary form-control" name="btnEditar">Editar</button>
                            </div>
                        </form>
                </div>
    </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
        <h3>Listado de Contactos</h3>
            <div class = "table-respnsive py2">
                <table class="table table-striped table-borderless">
                    <thead class="table-dark">
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Telefono</th>
                                <th>Correo</th>
                                <th>Direccion</th>
                                <th colspan="2">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for contacto in contactos%}
                                <tr>
                                    <td>{{contacto.id}}</td>
                                    <td>{{contacto.nombre}}</td>
                                    <td>{{contacto.apellido}}</td>
                                    <td>{{contacto.telefono}}</td>
                                    <td>{{contacto.correo}}</td>
                                    <td>{{contacto.direccion}}</td>
                                    <td><a href="{% url 'CRUD:editar' contacto.id %}" class="btn btn-info ">Editar</a></td>
                                    <td><a href="{% url 'CRUD:eliminar' contacto.id %}" class="btn btn-danger ">Eliminar</a></td>
                                </tr>
                            {%endfor%}
                        </tbody>
                </table>
            </div>
    </div>
</div>
</body>
</html>

CRUD/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>
        Contactos
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Gestion de Contactos</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CRUD:index' %}">
                  Contactos
                </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
              <!--Boton a la derecha del todo para el logout-->
              <li class="float-right">
                <a class="btn btn-danger nav-link float-right"
                href="{% url 'CRUD:logout_view' %}">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <h3>Crear Contacto</h3>
                <div class="card">
                    <div class="card-body">
                        <form action="/guardar_contacto" method="POST">
                            {%csrf_token%}
                            <div class="form-group mt-2">
                                <input type="text" class="form-control" name="txtnombre" placeholder="Nombre">
                            </div>
                            <div class="form-group mt-2">
                                <input type="text" class="form-control" name="txtapellido" placeholder="Apellido">
                            </div>
                            <div class="form-group mt-2">
                                <input type="text" class="form-control" name="txttelefono" placeholder="Telefono">
                            </div>
                            <div class="form-group mt-2">
                                <input type="text" class="form-control" name="txtcorreo" placeholder="Correo">
                            </div>
                            <div class="form-group mt-2">
                                <input type="text" class="form-control" name="txtdireccion" placeholder="Direccion">
                            <div class="form-group mt-3">
                                <button type="submit" class="btn btn-success form-control" name="btnGuardar">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
                <h3>Listado de Contactos</h1>
                <div class = "table-respnsive py2">
                    <table class="table table-striped table-borderless">
                        <thead class="table-dark">
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Telefono</th>
                                <th>Correo</th>
                                <th>Direccion</th>
                                <th colspan="2">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for contacto in contactos%}
                                <tr>
                                    <td>{{contacto.id}}</td>
                                    <td>{{contacto.nombre}}</td>
                                    <td>{{contacto.apellido}}</td>
                                    <td>{{contacto.telefono}}</td>
                                    <td>{{contacto.correo}}</td>
                                    <td>{{contacto.direccion}}</td>
                                    <td><a href="{% url 'CRUD:editar' contacto.id %}" class="btn btn-info ">Editar</a></td>
                                    <td><a href="{% url 'CRUD:eliminar' contacto.id %}" class="btn btn-danger ">Eliminar</a></td>
                                </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>